### PR TITLE
Added comic 832 to the list of large comics

### PR DESCRIPTION
**Pull request by 42SK**
I just found another large comic.

### CODE REVIEW

**Comment by T-Rex96** [comment]
Nice. When i started adding this feature, I just used the large comic list from explainxkcd (http://www.explainxkcd.com/wiki/index.php/Category:Large_drawings), seems like it is pretty incomplete.

**Comment by T-Rex96** [comment]
I resized the image so that it's smaller than 4096x4096 and mirrored it on imgur, so that it can be displayed in android.

**Comment by 42SK** [comment]
I am a bit confused. Why does the image have to be smaller than 4096x4096?
I tested the application with the unscaled version of the image and it didn't seem to cause any problems.

**Comment by T-Rex96** [comment]
It gave me this error on my device:

´´´
12-25 11:24:50.986 926-957/de.tap.easy_xkcd W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2040x4614, max=4096x4096)
´´´

**Comment by 42SK** [comment]
That's weird. I'm not getting any errors. Everything seems to work just fine.
Perhaps this is somehow related to your device?

**Comment by 42SK** [comment]
I've just tested this on a few devices.
I don't get any errors on devices running Android 6.0 or 5.0, but I get an `java.lang.OutOfMemoryError` on devices running Android 4.1.
However, there is still no error form the `OpenGLRenderer`.

**Comment by 42SK** [comment]
As far as I can tell, this doesn't seem to be affecting all devices.
Perhaps we should simply surround the relevant code with a try/catch block.

**Comment by T-Rex96** [comment]
Happens on my Nexus 5x, Nexus 5 and Nexus 7. I don't think try/catch would work, since the app does not actually crash - the ImageView just stays blank and the error message appears in the log.

**Pull request merged**
