### PR TITLE
Add adaptive icon

### LINKED ISSUE #124: FR: Adaptive icon
Api 26 introduced adaptive icons where background and foreground are two different images.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixed #124 

I just see that the image I used has too low resolution. Can you send me the image you used for the icon?

### CODE REVIEW

**Comment by T-Rex96** [comment]
Hi, sorry it took me so long to answer. [This](https://github.com/T-Rex96/Easy_xkcd/blob/master/app/src/main/ic_easy_xkcd_def-web.png) is actually the highest resolution I have for the icon, if you want a higher res you should ask @Thunderbottom since he's the one who designed the current version.

**Comment by Thunderbottom** [comment]
The one you linked should be fine for creating an icon!

**Comment by Thunderbottom** [comment]
also if you want to upscale an image, just run it through [waifu2x](http://waifu2x.udp.jp) once

**Comment by mueller-ma** [comment]
@Thunderbottom Do you have the image without background?

**Comment by Thunderbottom** [comment]
I do not, sorry. I made it a while ago.

**Comment by ChildishGiant** [comment]
I could work on an svg version if wanted. I'd suggest a re-styling to make the linework smoother

**Comment by mueller-ma** [comment]
@ChildishGiant Thanks. I just need the head as svg, background and shadow are generated by the Android Studio Icon Assistant. Can you post the svg as Github gist?

**Comment by ChildishGiant** [comment]
[Here ya go](https://gist.github.com/ChildishGiant/5a7ad4175bca8911655812b6410bfa98)

**Comment by mueller-ma** [comment]
> Here ya go

I meant the outline svg.

**Comment by ChildishGiant** [comment]
btw if you open up inkscape it's super easy to separate them 😉 [HERE ya go](https://gist.github.com/ChildishGiant/49bf9cc9282635ec73e2345048e5dd55)

**Comment by mueller-ma** [comment]
Thanks @ChildishGiant!
@T-Rex96 from my side this PR is ready to merge. I had to bump the build tools in order to create an adaptive icon, but I didn't bump targetSdk, so no code modifications need to be made.

**Comment by Thunderbottom** [comment]
I think you should consolidate all the commits into one for cleaner history

**Comment by T-Rex96** [comment]
Sorry that it took so long, but great work :)

**Pull request merged**
