### PR TITLE
New materialized icons proposition

### PR DESCRIPTION
**Pull request by balzathor**
I feel like the icons are not so pretty, so here's something cleaner, if you want something else I can make it however you want

### CODE REVIEW

**Comment by T-Rex96** [comment]
Great work, but I think perhaps it would look even better with some shadows (which would also make it more material, right?). 

Could you make an improved version of the old icon, too? We could then let the users decide which one they like more.

**Comment by balzathor** [comment]
Yes I'll make some more and then let the user pick what they want.

**Comment by balzathor** [comment]
And, yeah the shadows are already added as per material design standards, more shadows will make it more darker around the shadow area, and it won't feel good on smaller devices

**Comment by balzathor** [comment]
Can you send me a high res png of just the outline of that artist on the old icon?

**Comment by T-Rex96** [comment]
Sweet :)

**Comment by balzathor** [comment]
Aight, I'm done adding icons, added more colors and a few more icon options, I feel this much should be enough.

**Comment by T-Rex96** [comment]
Cool, I'll create a google survey and add a snackbar to the app, so that the users can decide.

**Comment by balzathor** [comment]
Or you could just add all of them to the app, and then through settings you can allow people to set the icon they want to

**Comment by balzathor** [comment]
You might not want to have a mad 1% user base just because you did not have the icon they wanted

**Comment by T-Rex96** [comment]
Is that even possible in Android? Looking at some stackoverflow questions there only seem to be some hacky workarounds.

**Comment by balzathor** [comment]
Yes, they'll have to reboot the device though, if you want I can help you with it.

**Comment by balzathor** [comment]
It also works without reboot if they have a launcher installed.

**Comment by T-Rex96** [comment]
That would be great! But in that case let's just adjust the old icon to the material grid (and maybe tune the shadow a bit) and let it be the default one, while the user can choose a new one if he likes too

**Comment by balzathor** [comment]
Alright, I'll start right away. Just keep a backup of the old icon

**Comment by balzathor** [comment]
Also, you might want to add a Continuous integration to your application so you can keep a track of the build. I can help you with it too.

**Comment by balzathor** [comment]
[This](http://stackoverflow.com/a/15249542) still works fine till now, you can also try others to set the icon

**Comment by T-Rex96** [comment]
I'll look into it

**Comment by T-Rex96** [comment]
So can you put the color back to your improved icon (https://github.com/balzathor/Easy_xkcd/commit/23bd4c57428c223b7959cfa6210d22d1e82feed3) so I can use it as the default one?

**Comment by balzathor** [comment]
Hey man, I could do it but its night right now in Asia and I'm on phone. Can you leave this request as it is until I come back from college tomorrow? I'll help you with the rest of the things

**Comment by T-Rex96** [comment]
Sure, no rush ;)

**Comment by balzathor** [comment]
Okay so I'll make the icon now

**Comment by balzathor** [comment]
Done

**Comment by T-Rex96** [comment]
Sweet!

**Comment by balzathor** [comment]
Have you released this on Play Store?

**Comment by T-Rex96** [comment]
Yep

**Pull request merged**
