### PR TITLE
Add feature - Export Favorites list as text

### PR DESCRIPTION
**Pull request by acropup**
Added ability to export favorites list as text. Available under the
Advanced settings. Exports in a format like this:
```
627 - Tech Support Cheat Sheet
641 - Free
645 - RPS
675 - Revolutionary
688 - Self-Description
```

The user can choose any app to export to that supports text/plain, such
as Gmail or a note-taking app.

Note that my computer and phone are not set up for Android development,
so I haven't tested or even compiled this, but it's a pretty simple
feature and hopefully I have done everything right. I used google
translate to add new text to the other languages, but I cannot vouch for
their accuracy.

### CODE REVIEW

**Comment by T-Rex96** [comment]
Good work :) 
I don't really like using google translator, I usually just use the English strings for Czech/Serbian and translate the German one by myself. This also makes it easier for the translators to see which strings are new and have to be translated.

**Comment by acropup** [comment]
Yeah, no worries, I don't blame you but I wasn't sure if you (or others) were translating manually, or with a tool. Should I change them back to English, or can we notify your translators directly?

**Comment by T-Rex96** [comment]
Yep it's manually, so just change them back to English. Not sure if you can send private messages on GitHub, so we'll just wait until they show up to translate it.

**Comment by acropup** [comment]
Ok, I removed the google translated strings and included them in this Pull Request. I think you can probably notify users by using the @ convention in a comment, like @T-Rex96.

**Pull request merged**
